In [4]:
import numpy as np

input_data = np.array([[0,0,1],
                      [0,1,1],
                      [1,0,1],
                      [1,1,1]])
output_labels = np.array([[0],
                         [1],
                         [1],
                         [0]])

print(input_data)
print(output_labels)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [5]:
def activate(x,deriv=False):
    if deriv==True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [6]:
synaptic_weight_0 = 2*np.random.random((3,4))-1
synaptic_weight_1 = 2*np.random.random((4,1))-1

print(synaptic_weight_0)
print(synaptic_weight_1)


[[ 0.68610878  0.93574537  0.46795475  0.6276663 ]
 [ 0.39341763  0.19693425  0.85935271 -0.36882672]
 [ 0.77610139 -0.20692954  0.05281964 -0.29818227]]
[[-0.59483963]
 [-0.09184022]
 [ 0.57502092]
 [-0.33971514]]


In [26]:
for j in range(1000000):
    
    layer_0 = input_data
    layer_1 = activate(np.dot(layer_0,synaptic_weight_0))
    layer_2 = activate(np.dot(layer_1,synaptic_weight_1))
    
    l2error = output_labels - layer_2
    
    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2error))))
    
    layer2_gradient = l2error*activate(layer_2, deriv=True)
    
    layer1_error = layer2_gradient.dot(synaptic_weight_1.T)
    
    layer1_gradient = layer1_error*activate(layer_1, deriv=True)
    
    synaptic_weight_1 += layer_1.T.dot(layer2_gradient)
    synaptic_weight_0 += layer_0.T.dot(layer1_gradient)

Error:0.0027229389569589234
Error:0.002608886595919481
Error:0.0025077927309901625
Error:0.0024173893366119244
Error:0.0023359264105237264
Error:0.0022620293737991583
Error:0.0021946016435364585
Error:0.002132756396740538
Error:0.0020757677286588547
Error:0.0020230350147841746
Error:0.001974056458233334
Error:0.0019284091515477894
Error:0.0018857338393603144
Error:0.0018457231267461666
Error:0.0018081122493495405
Error:0.0017726717729585882
Error:0.0017392017636179086
Error:0.0017075270908063266
Error:0.0016774936124779095
Error:0.0016489650528759491
Error:0.0016218204292935939
Error:0.0015959519173262137
Error:0.0015712630690222548
Error:0.0015476673170455916
Error:0.0015250867121688885
Error:0.0015034508522993233
Error:0.0014826959696415609
Error:0.0014627641491423262
Error:0.0014436026564881121
Error:0.001425163357969422
Error:0.0014074022177406357
Error:0.0013902788605696602
Error:0.0013737561902357912
Error:0.0013578000553997977
Error:0.001342378956127504
Error:0.00132746378535029

In [27]:
print(activate(np.dot(np.array([0, 1, 1]), synaptic_weight_0)))

[0.62867398 0.12199411 0.97581337 0.19231761]
